### ISSUE TITLE
High CPU usage when search doc because of space partitions locating at a single PS

### ISSUE THREAD

**Issue by miner-realm** [vearch/vearch#249]
1 vearch cluster mode, version: 3.2.0,  3 master, 3 router, 3 ps
2 space info shows all partitions locating on a single partition server
3 create space json:
`{"name": "vearchSpace_xxxxxxxx", "replica_num": 3, "partition_num": 9, "dynamic_schema": "strict", "engine": {"name": "gamma", "max_size": 1024000, "retrieval_type": "IVFPQ", "index_size": 50000}, "properties": {"key": {"type": "keyword", "index": true}, "time": {"type": "integer", "index": true}, "value": {"type": "vector", "dimension": 384, "format": "normalization"}}}`
4 how to assign partitions to different partition server

**Comment by kuailelijuan** [comment]
First you create 9 partitions, each partition has 3 replicas, and then there are only 3 ps services. So each ps service will have a replicas of these 9 partitions, which is normal logic. When querying, you can specify the query "client_type": "random", so that all replicas can provide retrieval services.
